version: '3.9'
volumes:
  nextcloud:
  db:
  certs:
  acme:
  vhost:

services:
  ssl: 
    hostname: ssl
    image: nginxproxy/acme-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/tmp/docker.sock:ro
  reverse-proxy:
    hostname: nextcloud-reverse-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment: 
      - DHPARAM_GENERATION=false
      - TZ=${TZ}

  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    restart: always
    environment: 
      - TZ=${TZ}

  nextcloud-db:
    image: mariadb
    hostname: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - TZ=${TZ}

  app:
    image: nextcloud:22
    restart: always
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    ports:
      - 8080:80
      - 8081:443
    links:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html      
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - TZ=${TZ}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}

